version: '3.8'

services:
  zender-wa:
    image: renatoascencio/zender-wa:optimized
    container_name: zender-wa-optimized
    restart: unless-stopped

    # Port mapping
    ports:
      - "443:443"

    # Environment variables
    environment:
      - PCODE=${PCODE}
      - KEY=${KEY}
      - PORT=${PORT:-443}
      - DOWNLOAD_URL_OVERRIDE=${DOWNLOAD_URL_OVERRIDE:-}

    # Volume mapping for persistent data
    volumes:
      - whatsapp_data:/data/whatsapp-server
      - ./monitoring:/data/whatsapp-server/monitoring:ro
      - ./utils:/data/whatsapp-server/utils:ro

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

    # Health check
    healthcheck:
      test: ["/usr/local/bin/status-wa", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

    # Security options
    security_opt:
      - no-new-privileges:true

    # Network configuration
    networks:
      - zender-network

  # Optional: Log aggregation service
  log-monitor:
    image: alpine:3.19
    container_name: zender-log-monitor
    restart: unless-stopped

    volumes:
      - whatsapp_data:/data/whatsapp-server:ro
      - ./monitoring:/scripts:ro

    command: >
      sh -c "
        apk add --no-cache bash curl &&
        while true; do
          /scripts/log-monitor.sh analyze 5 || true
          sleep 300
        done
      "

    depends_on:
      - zender-wa

    networks:
      - zender-network

  # Optional: Metrics exporter for Prometheus
  metrics-exporter:
    image: alpine:3.19
    container_name: zender-metrics
    restart: unless-stopped

    volumes:
      - whatsapp_data:/data/whatsapp-server:ro

    ports:
      - "9090:9090"

    command: >
      sh -c "
        apk add --no-cache bash curl jq &&
        while true; do
          if [ -f /data/whatsapp-server/metrics.json ]; then
            echo '# HELP whatsapp_memory_mb Memory usage in MB' > /tmp/metrics.txt
            echo '# TYPE whatsapp_memory_mb gauge' >> /tmp/metrics.txt
            echo \"whatsapp_memory_mb \$(cat /data/whatsapp-server/metrics.json | jq -r '.resources.memory_mb // 0')\" >> /tmp/metrics.txt

            echo '# HELP whatsapp_cpu_percent CPU usage percentage' >> /tmp/metrics.txt
            echo '# TYPE whatsapp_cpu_percent gauge' >> /tmp/metrics.txt
            echo \"whatsapp_cpu_percent \$(cat /data/whatsapp-server/metrics.json | jq -r '.resources.cpu_percent // 0')\" >> /tmp/metrics.txt

            echo '# HELP whatsapp_uptime_seconds Service uptime in seconds' >> /tmp/metrics.txt
            echo '# TYPE whatsapp_uptime_seconds counter' >> /tmp/metrics.txt
            echo \"whatsapp_uptime_seconds \$(cat /data/whatsapp-server/metrics.json | jq -r '.service.uptime_seconds // 0')\" >> /tmp/metrics.txt

            nc -l -p 9090 -e cat /tmp/metrics.txt || true
          fi
          sleep 10
        done
      "

    depends_on:
      - zender-wa

    networks:
      - zender-network

volumes:
  whatsapp_data:
    driver: local

networks:
  zender-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16