global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@zender-wa.local'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
  - name: 'default'
    webhook_configs:
    - url: 'http://webhook-url/alerts'

  - name: 'critical-alerts'
    email_configs:
    - to: 'admin@example.com'
      subject: '🚨 CRITICAL Alert: {{ .GroupLabels.alertname }}'
      body: |
        {{ range .Alerts }}
        Alert: {{ .Annotations.summary }}
        Description: {{ .Annotations.description }}
        {{ end }}

    slack_configs:
    - api_url: 'YOUR_SLACK_WEBHOOK_URL'
      channel: '#alerts'
      title: '🚨 Critical Alert'
      text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: 'warning-alerts'
    slack_configs:
    - api_url: 'YOUR_SLACK_WEBHOOK_URL'
      channel: '#warnings'
      title: '⚠️ Warning'
      text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'