name: Build All Release Images

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para obtener todos los tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get all tags
        id: tags
        run: |
          TAGS=$(git tag -l | grep '^v' | sort -V | tr '\n' ' ')
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          LATEST_TAG=$(git tag -l | grep '^v' | sort -V | tail -n1)
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Build and push v2.1.2
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            renatoascencio/zender-wa:v2.1.2
          build-args: |
            VERSION=v2.1.2
            BUILD_DATE=${{ env.BUILD_DATE }}

      - name: Build and push v2.1.3
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            renatoascencio/zender-wa:v2.1.3
          build-args: |
            VERSION=v2.1.3
            BUILD_DATE=${{ env.BUILD_DATE }}

      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            renatoascencio/zender-wa:latest
            renatoascencio/zender-wa:stable
          build-args: |
            VERSION=${{ steps.tags.outputs.latest_tag }}
            BUILD_DATE=${{ env.BUILD_DATE }}

      - name: Create optimized tag
        run: |
          docker buildx imagetools create \
            --tag renatoascencio/zender-wa:optimized \
            renatoascencio/zender-wa:v2.1.3

      - name: Summary
        run: |
          echo "## 📦 Docker Images Published" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Version Tags:" >> $GITHUB_STEP_SUMMARY
          echo "- \`renatoascencio/zender-wa:v2.1.2\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`renatoascencio/zender-wa:v2.1.3\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Special Tags:" >> $GITHUB_STEP_SUMMARY
          echo "- \`renatoascencio/zender-wa:latest\` (points to v2.1.3)" >> $GITHUB_STEP_SUMMARY
          echo "- \`renatoascencio/zender-wa:stable\` (points to v2.1.3)" >> $GITHUB_STEP_SUMMARY
          echo "- \`renatoascencio/zender-wa:optimized\` (points to v2.1.3)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Platforms:" >> $GITHUB_STEP_SUMMARY
          echo "- linux/amd64" >> $GITHUB_STEP_SUMMARY
          echo "- linux/arm64" >> $GITHUB_STEP_SUMMARY
          echo "- linux/arm/v7" >> $GITHUB_STEP_SUMMARY