name: ShellCheck
on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: |
          files=$(git ls-files '*.sh')
          if [ -n "$files" ]; then
            echo "Checking shell scripts with ShellCheck..."
            # Exclude common warnings that are acceptable in our context
            shellcheck \
              -e SC2034 \
              -e SC2164 \
              -e SC2086 \
              -e SC2004 \
              -e SC2006 \
              -e SC2046 \
              -e SC2068 \
              -e SC2206 \
              -e SC2207 \
              -e SC2230 \
              $files || {
                echo "ShellCheck found issues. Review and fix, or add exclusions if acceptable."
                echo "Common exclusions already applied:"
                echo "  SC2034: Unused variables"
                echo "  SC2164: cd without error checking"
                echo "  SC2086: Double quote to prevent globbing"
                echo "  And others for Docker/script context..."
                exit 1
              }
            echo "✅ All shell scripts passed ShellCheck!"
          else
            echo "No shell scripts to check."
          fi
