name: ShellCheck
on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: warning
          ignore_paths: |
            .git
            node_modules
          ignore_names: |
            *.bak
            *.old
          additional_files: |
            entrypoint.sh
            scripts/*.sh
            monitoring/*.sh
            utils/*.sh
            security/*.sh
            tests/*.sh
            tests/unit/*.sh
        env:
          SHELLCHECK_OPTS: -e SC2034 -e SC2164 -e SC2086 -e SC2004 -e SC2006 -e SC2046 -e SC2068 -e SC2206 -e SC2207 -e SC2230 -e SC2155 -e SC2038 -e SC2012 -e SC1091 -e SC2153 -e SC2016
