name: ShellCheck
on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: |
          files=$(git ls-files '*.sh')
          if [ -n "$files" ]; then
            echo "Checking shell scripts with ShellCheck..."
            echo "Files to check: $files"

            # Run ShellCheck with exclusions for each file
            for file in $files; do
              echo "Checking $file..."
              shellcheck -e SC2034 -e SC2164 -e SC2086 -e SC2004 -e SC2006 -e SC2046 -e SC2068 -e SC2206 -e SC2207 -e SC2230 "$file" || {
                echo "❌ ShellCheck failed for $file"
                exit 1
              }
              echo "✅ $file passed"
            done

            echo "🎉 All shell scripts passed ShellCheck!"
          else
            echo "No shell scripts to check."
          fi
